### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by bananakid** [otuncelli/Portable-Document-Format-Plugin-for-Paint.NET#2] opened 2024-05-07 12:20 UTC
I downloaded [Portable-Document-Format-Plugin](https://github.com/otuncelli/Portable-Document-Format-Plugin-for-Paint.NET) project and the corresponding [PDFiumSharp](https://github.com/otuncelli/PDFiumSharp/tree/3deaa32817d1e737453646b95b6e5bd5a2070e9e) project.

Then I put PDFiumSharp project files into `Portable-Document-Format-Plugin\PDFiumSharp` directory.

Then I downloaded [paint.net 4.2.16](https://www.filepuma.com/download/paint.net_4.2.16-29892/), installed it and copied `PaintDotNet.Base.dll`, `PaintDotNet.Base.pdb`, `PaintDotNet.Core.dll`, `PaintDotNet.Core.pdb`, `PaintDotNet.Data.dll`, `PaintDotNet.Data.pdb` to `Portable-Document-Format-Plugin` directory.

Then I opened `Portable-Document-Format-Plugin\PdfFileTypePlugin.sln` and did used `Run Custom Tool` on `FPDF_Typedefs.tt` and `PDFium.tt` of `PDFiumSharp → Types` (as explained in [this issue](https://github.com/ArgusMagnus/PDFiumSharp/issues/16#issuecomment-575113820)).

However, when I attempt to build `PdfFileType` project, I receive 3 errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Surface' does not contain a definition for 'Fill' and no accessible extension method 'Fill' accepting a first argument of type 'Surface' could be found (are you missing a using directive or an assembly reference?)	PdfFileType (net5.0-windows)	C:\Portable-Document-Format-Plugin\PdfFileType\Import\PdfImport.cs	287	Active
Error	CS1061	'Surface' does not contain a definition for 'Fill' and no accessible extension method 'Fill' accepting a first argument of type 'Surface' could be found (are you missing a using directive or an assembly reference?)	PdfFileType (net5.0-windows)	C:\Portable-Document-Format-Plugin\PdfFileType\Export\PdfExporter.cs	99	Active
Error	CS1061	'Surface' does not contain a definition for 'Fill' and no accessible extension method 'Fill' accepting a first argument of type 'Surface' could be found (are you missing a using directive or an assembly reference?)	PdfFileType (net5.0-windows)	C:\Portable-Document-Format-Plugin\PdfFileType\Export\PdfExporter.cs	108	Active
```

How can I workaround this?

**Comment by otuncelli** [comment] 2024-05-07 20:03
Hi,

paint.net 4.2.16 utilizes .NET Framework 4.7. However, the errors you're encountering are for .NET 5 (which is for paint.net versions >=5). This project employs multitargeting, compiling the plugin for both paint.net 4 and paint.net 5 simultaneously. Nonetheless, you can only have one paint.net version installed on your system. In my case, I had installed paint.net 5, but I hadn't installed paint.net 4.2.16. Instead, I had only copied its libraries into a folder. The project configuration assumes paint.net 5 is installed by default.

The problem is,
You're attempting to use paint.net 4.2.16's assemblies to compile the plugin for paint.net 5, resulting in these errors.

Solution:
If you don't have paint.net 5 installed or don't want to compile against it you can edit the main project file (`PdfFileType.csproj`) and remove `net5.0-windows` from `TargetFrameworks`

There's also no need to copy those assemblies into the directory (which wouldn't have any effect); you can simply set the `PdnRoot` variable in the project file. It should point to your paint.net installation directory:
```xml
  <PropertyGroup Condition="'$(TargetFramework)'=='net47'">
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PdnRoot>D:\Backup\Programlar\paint.net_4216</PdnRoot> <!-- should point to your paint.net 4.2.16 installation folder -->
    <PluginDir>$(PdnRoot)\$(PluginType)s\</PluginDir>
  </PropertyGroup>
```

I plan to discontinue support for 4.2.16 and clean up the project soon.

**Comment by otuncelli** [comment] 2024-05-09 23:00
> To summarize, may I request a shorter filetype description for Save As… dialog for the upcoming updated build?

Sure. I'm leaving this issue open as a reminder.

**Comment by otuncelli** [comment] 2024-11-26 23:38
Fixed with the new release.

**Closed as completed by otuncelli** 2024-11-26 23:38 UTC
